#!/bin/bash
if [ "x$1$2" = x ]
then
	cat<<-EOF
	rc dev on|off
	
	dev:
	 s|Stereo
	 yk1.#.# // offiziell (TODO)
	 yk2.#.# // binär
	 tv
	 l|Licht
	EOF
	exit 1
fi

case "$1" in
	r | radio | s | stereo)
		if [ x$2 = xon ]; then
			rc433 24 00302BEA
		else
			rc433 24 00C02BEA
		fi
	;;
	tv)
		if [ x$2 = xon ]; then
			rc433 24 00302EEA
		else
			rc433 24 00C02EEA
		fi
	;;
	l | Licht)
		if [ x$2 = xon ]; then
			rc433 20 0x0000A00D
		else
			rc433 20 0x0008200D
		fi
	;;
	yk?.?.?)
		n1="${1:2:1}"
		n2="${1:4:1}"
		n3="${1:6:1}"
		on=0
		if [ "x$n1" = x1 ]
		then
			case "$n3" in
				1)
					n3=3;
				;;
				2)
					n3=1;
				;;
				3)
					n3=2;
				;;
				4)
					n3=4;
				;;
			esac;
		fi
		let n2=$((~n2 & 7))
			let n3=$((~n3 & 7))
		if [ x$2 = xon ]; then
			on=0
		else
			on=1
		fi
		rc433 12 "`printf "%x" $((0xf80 | $n2 << 4 | $n3 << 1 | $on))`"
		
	;;
esac